services:
  xtts:
    image: daswer123/xtts-api-server
    container_name: xtts-server
    ports:
      - "5002:8020"
    volumes:
      - ./xtts-data:/app/tts
    environment:
      - COQUI_TOS_AGREED=1
    restart: unless-stopped